### ISSUE TITLE
Typing event names and data like typed-emitter

### ISSUE THREAD

**Issue by leumasme** [Paul-Lazunko/chain-events#1]
Hey there!
I really want to use a middleware-like event system like this one, but im missing an option to better type the events.
[typed-emitter](https://www.npmjs.com/package/typed-emitter) for reference strictly types event names and corresponding event data.
This library seems to be exactly what i want functionality-wise, big props for that! It was the only library for this purpose i could find thats exactly what i want and not completely dead.
Would be great if this extended type support could be added.
Thanks
(Also, why are you not `await`ing next() in your examples in the readme, even though the handler is async?)

**Comment by leumasme** [comment]
I've hacked arround on it a bit and seem to have some working types.
I havent confirmed that this actually still works aside from the types, and removed type error checking for non-ts applications as well, so definetly not pullable, but if you want some reference on getting types to work, see [leumasme/chain-events](https://github.com/leumasme/chain-events)

**Comment by leumasme** [comment]
Okay, it seems that awaiting next isn't even supported as next does not return the executor promise, so running things after next if a deeper middleware does something async isnt even possible, so async middlewares are completely broken, despite what the examples suggest

**Comment by leumasme** [comment]
Also still broken is ANY_EVENT error handling, but this also seems to be broken by the library.
[Ever since commit b41fbd4](https://github.com/Paul-Lazunko/chain-events/commit/b41fbd447ec8b6d3f58e936207e143817276a2df#diff-93a9b84600d045cdada7a7917426b9cd7d89adaf56efbdf4f2051c7dcde0d9a5L92), the getErrorHandler function only called the ANY_EVENT error handler if no handler was found for this function - not just no event handler.
This means that, any function that has an event handler would not use the ANY_EVENT error handler, even if it does not have an error handler

**Comment by Paul-Lazunko** [comment]
@leumasme version v1.1.0 which includes provided updates was published. thank you for your contribution !
